(lang dune 1.11)
(allow_approximate_merlin)
(package
 (name phoenix_lib)
 (synopsis "My first Dune package!")
 (description "\| This is my first attempt at creating
              "\| a project with Dune.
))