(lang dune 2.5)
(using menhir 2.0)
;(allow_approximate_merlin)
(package
 (name phoenix2)
 (synopsis "My second Dune package!")
 (description "\| This is my second attempt at creating
              "\| a project with Dune.
))